# Give our client a name and point it to the Python server's port
grpc.client.faceswap-python-service.address=static://127.0.0.1:50051
grpc.client.faceswap-python-service.negotiation-type=plaintext

# Allow larger file uploads for high-res images (default is 1MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB